language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
matrix:
  include:
  - os: osx
    language: objective-c
  - os: osx
    language: objective-c
    env: PYENV_VERSION=pypy3.3-5.2-alpha1
  - os: osx
    language: objective-c
    env: PYENV_VERSION=pypy-5.4.1
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.12
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.5.2
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
deploy:
  provider: releases
  api_key:
    secure: Z5m7K1UVq0812nNtR+QAkUE3lxUwhMjM3EDWUOyPmfh0rmOsU2RgQ8oBfT1vatYfY8ExnrG4rRNWmwUqPEIzZmRLmw9zv+ixA3gcVPn6WbbMkwoeIurOPsC9wjgCckDFKYhMda8a92FSL2hVto3JPcRNTZnsKBR35Queray55SM=
  file: dist/*.whl
  file_glob: true
  on:
    repo: xattr/xattr
    tags: true
  skip_cleanup: true
